// Lb3AutoSrv10333.idl: источник языка IDL для Lb3AutoSrv10333
//

// Этот файл будет обработан средством MIDL для
// создание библиотеки типов ($handlersafeidlname$.tlb) и кода маршалирования.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(c33029b7-a92e-49e7-8b93-23353b280192),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IMyMath : IDispatch
{
	[id(1), helpstring("Fun91")] HRESULT Fun91([in] LONG x, [in] LONG y, [out, retval] LONG* result);
	[id(2), helpstring("Fun92")] HRESULT Fun92([in] FLOAT x, [in] FLOAT y, [out] FLOAT* result);
	[id(3), helpstring("Fun93")] HRESULT Fun93([in] DOUBLE in, [out] DOUBLE* out);
};
[
	uuid(7bb93608-2d7d-4c70-83f2-0c3fe2f53bde),
	version(1.0),
]
library Lb3AutoSrv10333Lib
{
	importlib("stdole2.tlb");
	[
		uuid(4f0059b0-9b5f-4311-833e-6dee5aeac2b0)
	]
	coclass MyMath
	{
		[default] interface IMyMath;
	};
};

import "shobjidl.idl";
